name: infoprovas
description: Repositório de provas do DCC-UFRJ.

version: 0.1.2+3

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_full_pdf_viewer: ^1.0.4
  http: ^0.12.0
  mysql1: ^0.16.3
  flutter_custom_tabs: ^0.6.0
  url_launcher: ^5.0.1

  sqflite: ^1.1.0
  path_provider: ^0.5.0
  shared_preferences: 0.5.0

  cupertino_icons: ^0.1.2
  bubble_tab_indicator: ^0.1.4
  dynamic_theme: ^1.0.1
  flutter_slidable: "^0.5.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
  fonts:
    - family : facebook
      fonts:
        - asset: assets/fonts/fb_icon.ttf
    - family : github
      fonts:
        - asset : assets/fonts/git_icon.ttf

  uses-material-design: true