name: project
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #flutter_pdf_viewer: ^0.0.7
  http: ^0.12.0
  cloud_firestore: ^0.9.0
  flutter_document_picker: ^1.4.0
  cupertino_icons: ^0.1.2
  url_launcher: ^4.2.0
  bubble_tab_indicator: ^0.1.4
  mysql1: ^0.16.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
  fonts:
    - family : facebook
      fonts:
        - asset: assets/fonts/FbIcon.ttf
    - family : github
      fonts:
        - asset : assets/fonts/GitIcon.ttf

  uses-material-design: true